### PR TITLE
Update hyprctl.py to fix hyprctl issue.

### PR DESCRIPTION
**Pull request by kaii-lb**
fixed new hyprctl json error. Just needs to remove first line of -j output from hyprctl and json parsing returns to normal :D

### CODE REVIEW

**Comment by loqusion** [comment]
Huh, that's odd. I'm on the latest version of hyprland and running `hyprctl -j getoption decoration:screen_shader | cut -d' ' -f2- | head -n -1 | tail -n +4` gets:

```
   "int": -9223372036854775807,
   "float": -340282346638528859811704183484516925440.000000,
   "str": "[[EMPTY]]",
   "data": "0x0"
}
```

...which isn't valid JSON.

Could you show me the output for `hyprctl -j getoption decoration:screen_shader` and `pacman -Qi hyprland`?

**Comment by loqusion** [comment]
It seems that this is an upstream issue, which I believe was fixed in https://github.com/hyprwm/Hyprland/commit/47430411d69d6cba9241775f0ea11722afeb74d7 — the problem is, it hasn't yet been included in a stable release. I'll add a workaround patch that's also compatible with the new fix.

**Comment by loqusion** [comment]
Should be fixed in https://github.com/loqusion/hyprshade/tree/v0.8.4 — try it and lmk if it works.

**Comment by kaii-lb** [comment]
yep it works! thanks for the effort man

**Pull request closed without merging**
